// Значения по умолчанию, схемы и README. Правишь дефолты — тебе сюда; они
// применяются только при первом запуске (или после удаления Settings.json).
//
// README и схемы перезаписываются при КАЖДОЙ загрузке: пока README писался только
// при первом запуске, после обновления плагина он описывал старую версию.
#include "core/config.h"

namespace ch {

// Дефолты обезличены сознательно: плагин ставят чужие люди, и первый запуск
// не имеет права попытаться подключиться к чужой базе.
std::string DefaultSettingsJson() {
    return
        "{\n"
        "  \"$schema\": \"./Settings.schema.json\",\n"
        "\n"
        "  \"Debug\": false,\n"
        "  \"ServerId\": 1,\n"
        "  \"DefaultLang\": \"RU\",\n"
        "\n"
        "  // Пояс, в котором время видят ИГРОКИ. В базе время ВСЕГДА в UTC.\n"
        "  // Эта сборка понимает \"UTC\", \"Local\" и смещение вида \"+03:00\".\n"
        "  \"DisplayTimeZone\": \"UTC\",\n"
        "\n"
        "  \"Server\": {\n"
        "    // Публичный адрес сервера: \"ip:port\" или \"host:port\".\n"
        "    // Процесс сервера своего публичного адреса не знает.\n"
        "    \"PublicAddress\": \"\"\n"
        "  },\n"
        "\n"
        "  \"Database\": {\n"
        "    \"Host\": \"127.0.0.1\",\n"
        "    \"Port\": 3306,\n"
        "    \"Database\": \"connect_history\",\n"
        "    \"User\": \"\",\n"
        "    \"Password\": \"\",\n"
        "    \"SslMode\": \"Preferred\",\n"
        "    \"TablePrefix\": \"ch_\",\n"
        "    \"ConnectionTimeoutSeconds\": 10,\n"
        "    \"CommandTimeoutSeconds\": 30\n"
        "  },\n"
        "\n"
        "  \"Collect\": {\n"
        "    \"GeoIp\": true,\n"
        "    \"PlayerIp\": true,\n"
        "    \"IpHash\": true,\n"
        "    // Пустая соль = хеширование выключено: без неё хеш IPv4 обратим перебором\n"
        "    \"IpHashSalt\": \"\",\n"
        "    \"MatchStats\": true,\n"
        "    \"Ping\": true,\n"
        "    \"CountSpectatorTime\": true,\n"
        "    \"NicknameHistory\": true,\n"
        "    \"PlayerAggregates\": true,\n"
        "    \"OnlineSnapshots\": true,\n"
        "    \"OnlineSnapshotIntervalSeconds\": 300,\n"
        "    \"PingSampleIntervalSeconds\": 30\n"
        "  },\n"
        "\n"
        "  \"Storage\": {\n"
        "    \"SpoolEnabled\": true,\n"
        "    \"SpoolMaxEntries\": 20000,\n"
        "    \"RetryAttempts\": 3,\n"
        "    \"RetryDelaySeconds\": 5\n"
        "  },\n"
        "\n"
        "  \"Commands\": {\n"
        "    \"PlayerCommandsEnabled\": true,\n"
        "    \"CooldownSeconds\": 10,\n"
        "    \"LastSeenLimit\": 5\n"
        "  }\n"
        "}\n";
}

// Ключи и теги совпадают с C#-целями: один и тот же Messages.json обязан
// работать под любой из трёх реализаций.
std::string DefaultMessagesJson() {
    return
        "{\n"
        "  \"$schema\": \"./Messages.schema.json\",\n"
        "\n"
        "  \"Messages\": {\n"
        "    \"prefix\": {\n"
        "      \"RU\": \"{GREEN}[История]{DEFAULT} \",\n"
        "      \"EN\": \"{GREEN}[History]{DEFAULT} \"\n"
        "    },\n"
        "    \"playtime\": {\n"
        "      \"RU\": \"{prefix}Наиграно: {GOLD}{TOTAL}{DEFAULT}, заходов: {GOLD}{SESSIONS}{DEFAULT}, первый заход: {GOLD}{FIRST}\",\n"
        "      \"EN\": \"{prefix}Playtime: {GOLD}{TOTAL}{DEFAULT}, sessions: {GOLD}{SESSIONS}{DEFAULT}, first seen: {GOLD}{FIRST}\"\n"
        "    },\n"
        "    \"playtime_current\": {\n"
        "      \"RU\": \"{prefix}Текущая сессия: {GOLD}{CURRENT}\",\n"
        "      \"EN\": \"{prefix}Current session: {GOLD}{CURRENT}\"\n"
        "    },\n"
        "    \"lastseen_header\": {\n"
        "      \"RU\": \"{prefix}Последние заходы:\",\n"
        "      \"EN\": \"{prefix}Recent sessions:\"\n"
        "    },\n"
        "    \"lastseen_row\": {\n"
        "      \"RU\": \" {GREY}{DATE}{DEFAULT} — {GOLD}{DURATION}{DEFAULT} на {LIGHTBLUE}{MAP}\",\n"
        "      \"EN\": \" {GREY}{DATE}{DEFAULT} — {GOLD}{DURATION}{DEFAULT} on {LIGHTBLUE}{MAP}\"\n"
        "    },\n"
        "    \"no_data\": {\n"
        "      \"RU\": \"{prefix}{GREY}Данных пока нет\",\n"
        "      \"EN\": \"{prefix}{GREY}No data yet\"\n"
        "    },\n"
        "    \"cooldown\": {\n"
        "      \"RU\": \"{prefix}{RED}Подождите {SECONDS} сек.\",\n"
        "      \"EN\": \"{prefix}{RED}Wait {SECONDS} sec.\"\n"
        "    },\n"
        "    \"db_error\": {\n"
        "      \"RU\": \"{prefix}{RED}База данных недоступна\",\n"
        "      \"EN\": \"{prefix}{RED}Database is unavailable\"\n"
        "    }\n"
        "  }\n"
        "}\n";
}

std::string SettingsSchemaJson() {
    return
        "{\n"
        "  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n"
        "  \"title\": \"ConnectHistory Settings\",\n"
        "  \"type\": \"object\",\n"
        "  \"additionalProperties\": false,\n"
        "  \"properties\": {\n"
        "    \"$schema\": { \"type\": \"string\" },\n"
        "    \"Debug\": { \"type\": \"boolean\" },\n"
        "    \"ServerId\": { \"type\": \"integer\", \"minimum\": 0 },\n"
        "    \"DefaultLang\": { \"type\": \"string\" },\n"
        "    \"DisplayTimeZone\": {\n"
        "      \"type\": \"string\",\n"
        "      \"description\": \"UTC, Local или смещение вида +03:00. На базу не влияет.\"\n"
        "    },\n"
        "    \"Server\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": { \"PublicAddress\": { \"type\": \"string\" } }\n"
        "    },\n"
        "    \"Database\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": {\n"
        "        \"Host\": { \"type\": \"string\" },\n"
        "        \"Port\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 65535 },\n"
        "        \"Database\": { \"type\": \"string\" },\n"
        "        \"User\": { \"type\": \"string\" },\n"
        "        \"Password\": { \"type\": \"string\" },\n"
        "        \"SslMode\": { \"enum\": [\"None\", \"Preferred\", \"Required\"] },\n"
        "        \"TablePrefix\": { \"type\": \"string\", \"pattern\": \"^[A-Za-z0-9_]{0,16}$\" },\n"
        "        \"ConnectionTimeoutSeconds\": { \"type\": \"integer\", \"minimum\": 1 },\n"
        "        \"CommandTimeoutSeconds\": { \"type\": \"integer\", \"minimum\": 1 }\n"
        "      }\n"
        "    },\n"
        "    \"Collect\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": {\n"
        "        \"GeoIp\": { \"type\": \"boolean\" },\n"
        "        \"PlayerIp\": { \"type\": \"boolean\" },\n"
        "        \"IpHash\": { \"type\": \"boolean\" },\n"
        "        \"IpHashSalt\": { \"type\": \"string\" },\n"
        "        \"MatchStats\": { \"type\": \"boolean\" },\n"
        "        \"Ping\": { \"type\": \"boolean\" },\n"
        "        \"CountSpectatorTime\": { \"type\": \"boolean\" },\n"
        "        \"NicknameHistory\": { \"type\": \"boolean\" },\n"
        "        \"PlayerAggregates\": { \"type\": \"boolean\" },\n"
        "        \"OnlineSnapshots\": { \"type\": \"boolean\" },\n"
        "        \"OnlineSnapshotIntervalSeconds\": { \"type\": \"integer\", \"minimum\": 30 },\n"
        "        \"PingSampleIntervalSeconds\": { \"type\": \"integer\", \"minimum\": 5 }\n"
        "      }\n"
        "    },\n"
        "    \"Storage\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": {\n"
        "        \"SpoolEnabled\": { \"type\": \"boolean\" },\n"
        "        \"SpoolMaxEntries\": { \"type\": \"integer\", \"minimum\": 0 },\n"
        "        \"RetryAttempts\": { \"type\": \"integer\", \"minimum\": 1 },\n"
        "        \"RetryDelaySeconds\": { \"type\": \"integer\", \"minimum\": 1 }\n"
        "      }\n"
        "    },\n"
        "    \"Commands\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": {\n"
        "        \"PlayerCommandsEnabled\": { \"type\": \"boolean\" },\n"
        "        \"CooldownSeconds\": { \"type\": \"integer\", \"minimum\": 0 },\n"
        "        \"LastSeenLimit\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 25 }\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "}\n";
}

std::string MessagesSchemaJson() {
    return
        "{\n"
        "  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n"
        "  \"title\": \"ConnectHistory Messages\",\n"
        "  \"type\": \"object\",\n"
        "  \"properties\": {\n"
        "    \"$schema\": { \"type\": \"string\" },\n"
        "    \"Messages\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": {\n"
        "        \"type\": \"object\",\n"
        "        \"additionalProperties\": { \"type\": \"string\" }\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "}\n";
}

std::string ReadmeText() {
    return
        "ConnectHistory — история подключений и статистика игроков\n"
        "==========================================================\n"
        "Сборка под Metamod:Source (нативная, C++).\n"
        "\n"
        "Файлы в этом каталоге:\n"
        "  Settings.json          — основные настройки (в нём пароль от БД!)\n"
        "  Messages.json          — тексты команд ch_playtime / ch_lastseen\n"
        "  *.schema.json          — JSON Schema, редактор подскажет поля и опечатки\n"
        "\n"
        "ВАЖНО про безопасность\n"
        "  * Settings.json содержит пароль. Плагин выставляет ему права 600 (только владелец).\n"
        "  * Заведите для плагина ОТДЕЛЬНОГО пользователя MySQL с правами только\n"
        "    на его таблицы: SELECT, INSERT, UPDATE, CREATE, INDEX, ALTER.\n"
        "  * SslMode=Required, если база не на localhost: иначе ники, SteamID и IP\n"
        "    игроков идут по сети открытым текстом.\n"
        "\n"
        "Основные настройки\n"
        "  ServerId               — номер сервера. У РАЗНЫХ серверов должен быть разным.\n"
        "  Debug                  — подробный лог (пишет SteamID, ники и IP игроков).\n"
        "  DisplayTimeZone        — пояс, в котором время видят ИГРОКИ.\n"
        "                           Эта сборка понимает \"UTC\", \"Local\" и смещение \"+03:00\";\n"
        "                           имена IANA вроде \"Europe/Moscow\" не поддержаны — см. README\n"
        "                           цели metamod. В базе время ВСЕГДА в UTC.\n"
        "  Database.TablePrefix   — префикс таблиц, по умолчанию ch_\n"
        "  Server.PublicAddress   — публичный адрес сервера, \"ip:port\" или \"host:port\".\n"
        "                           Процесс сервера своего публичного адреса не знает:\n"
        "                           ConVar ip отдаёт адрес привязки сокета, обычно 0.0.0.0.\n"
        "\n"
        "Что собирается (секция Collect)\n"
        "  GeoIp                  — страна и город по GeoLite2 (.mmdb рядом с плагином)\n"
        "  PlayerIp               — полный IP игрока (персональные данные)\n"
        "  IpHash + IpHashSalt    — HMAC от IP: мультиаккаунты видно, адрес не хранится.\n"
        "                           Пустая соль = хеширование выключено.\n"
        "  MatchStats             — убийства, смерти, урон, MVP.\n"
        "                           score в этой цели НЕ собирается — колонка остаётся NULL.\n"
        "  Ping                   — средний/мин/макс пинг за сессию\n"
        "  CountSpectatorTime     — считать ли время в наблюдателях наигранным.\n"
        "                           false — из наигранного вычитается время вне игры.\n"
        "                           Само время всегда пишется в spectator_seconds.\n"
        "\n"
        "Если база недоступна\n"
        "  Записи копятся в pending-writes.jsonl рядом с плагином и досылаются\n"
        "  автоматически. Storage.SpoolMaxEntries ограничивает размер файла.\n"
        "\n"
        "Команды\n"
        "  ch_status     (только с консоли сервера) — связь с БД, очередь, последняя ошибка\n"
        "  ch_reload     (только с консоли сервера) — перечитать конфигурацию\n"
        "  ch_playtime                              — своё наигранное время\n"
        "  ch_lastseen                              — свои последние заходы\n"
        "\n"
        "Полное описание схемы БД и готовые SQL-запросы — docs/DATABASE.md,\n"
        "модуль для панели Flute CMS — docs/FLUTE_MODULE.md.\n";
}

}  // namespace ch
