// Defaults, JSON schemas and the README. Changing defaults? This is the place;
// they only apply on first run (or after Settings.json is deleted).
//
// The README and the schemas are rewritten on EVERY load: while the README was
// written on first run only, it described the previous version after every update.
#include "core/config.h"

namespace ch {

// Дефолты обезличены сознательно: плагин ставят чужие люди, и первый запуск
// не имеет права попытаться подключиться к чужой базе.
std::string DefaultSettingsJson() {
    return
        "{\n"
        "  \"$schema\": \"./Settings.schema.json\",\n"
        "\n"
        "  \"Debug\": false,\n"
        "  \"DefaultLang\": \"RU\",\n"
        "\n"
        "  // Пояс, в котором время видят ИГРОКИ. В базе время ВСЕГДА в UTC.\n"
        "  // Эта сборка понимает \"UTC\", \"Local\" и смещение вида \"+03:00\".\n"
        "  \"DisplayTimeZone\": \"UTC\",\n"
        "\n"
        "  \"Server\": {\n"
        "    // Номер сервера. У РАЗНЫХ серверов обязан различаться, иначе\n"
        "    // их истории склеятся в одну.\n"
        "    \"Id\": 1,\n"
        "\n"
        "    // Публичный адрес сервера: \"ip:port\" или \"host:port\".\n"
        "    // Процесс сервера своего публичного адреса не знает.\n"
        "    \"PublicAddress\": \"\"\n"
        "  },\n"
        "\n"
        "  \"Database\": {\n"
        "    \"Host\": \"127.0.0.1\",\n"
        "    \"Port\": 3306,\n"
        "    \"Database\": \"connect_history\",\n"
        "    \"User\": \"\",\n"
        "    \"Password\": \"\",\n"
        "    \"SslMode\": \"Preferred\",\n"
        "    \"TablePrefix\": \"ch_\",\n"
        "    \"ConnectionTimeoutSeconds\": 10,\n"
        "    \"CommandTimeoutSeconds\": 30\n"
        "  },\n"
        "\n"
        "  \"Collect\": {\n"
        "    \"GeoIp\": true,\n"
        "    \"PlayerIp\": true,\n"
        "    \"IpHash\": true,\n"
        "    // Пустая соль = хеширование выключено: без неё хеш IPv4 обратим перебором\n"
        "    \"IpHashSalt\": \"\",\n"
        "    \"MatchStats\": true,\n"
        "    \"Ping\": true,\n"
        "    \"CountSpectatorTime\": true,\n"
        "    \"NicknameHistory\": true,\n"
        "    \"PlayerAggregates\": true,\n"
        "    \"OnlineSnapshots\": true,\n"
        "    \"OnlineSnapshotIntervalSeconds\": 300,\n"
        "    \"PingSampleIntervalSeconds\": 30\n"
        "  },\n"
        "\n"
        "  \"Storage\": {\n"
        "    \"SpoolEnabled\": true,\n"
        "    \"SpoolMaxEntries\": 20000,\n"
        "    \"RetryAttempts\": 3,\n"
        "    \"RetryDelaySeconds\": 5\n"
        "  },\n"
        "\n"
        "  \"Commands\": {\n"
        "    \"PlayerCommandsEnabled\": true,\n"
        "    \"CooldownSeconds\": 10,\n"
        "    \"LastSeenLimit\": 5\n"
        "  }\n"
        "}\n";
}

// Ключи и теги совпадают с C#-целями: один и тот же Messages.json обязан
// работать под любой из трёх реализаций.
std::string DefaultMessagesJson() {
    return
        "{\n"
        "  \"$schema\": \"./Messages.schema.json\",\n"
        "\n"
        "  \"Messages\": {\n"
        "    \"prefix\": {\n"
        "      \"RU\": \"{GREEN}[История]{DEFAULT} \",\n"
        "      \"EN\": \"{GREEN}[History]{DEFAULT} \"\n"
        "    },\n"
        "    \"playtime\": {\n"
        "      \"RU\": \"{prefix}Наиграно: {GOLD}{TOTAL}{DEFAULT}, заходов: {GOLD}{SESSIONS}{DEFAULT}, первый заход: {GOLD}{FIRST}\",\n"
        "      \"EN\": \"{prefix}Playtime: {GOLD}{TOTAL}{DEFAULT}, sessions: {GOLD}{SESSIONS}{DEFAULT}, first seen: {GOLD}{FIRST}\"\n"
        "    },\n"
        "    \"playtime_current\": {\n"
        "      \"RU\": \"{prefix}Текущая сессия: {GOLD}{CURRENT}\",\n"
        "      \"EN\": \"{prefix}Current session: {GOLD}{CURRENT}\"\n"
        "    },\n"
        "    \"lastseen_header\": {\n"
        "      \"RU\": \"{prefix}Последние заходы:\",\n"
        "      \"EN\": \"{prefix}Recent sessions:\"\n"
        "    },\n"
        "    \"lastseen_row\": {\n"
        "      \"RU\": \" {GREY}{DATE}{DEFAULT} — {GOLD}{DURATION}{DEFAULT} на {LIGHTBLUE}{MAP}\",\n"
        "      \"EN\": \" {GREY}{DATE}{DEFAULT} — {GOLD}{DURATION}{DEFAULT} on {LIGHTBLUE}{MAP}\"\n"
        "    },\n"
        "    \"no_data\": {\n"
        "      \"RU\": \"{prefix}{GREY}Данных пока нет\",\n"
        "      \"EN\": \"{prefix}{GREY}No data yet\"\n"
        "    },\n"
        "    \"cooldown\": {\n"
        "      \"RU\": \"{prefix}{RED}Подождите {SECONDS} сек.\",\n"
        "      \"EN\": \"{prefix}{RED}Wait {SECONDS} sec.\"\n"
        "    },\n"
        "    \"db_error\": {\n"
        "      \"RU\": \"{prefix}{RED}База данных недоступна\",\n"
        "      \"EN\": \"{prefix}{RED}Database is unavailable\"\n"
        "    }\n"
        "  }\n"
        "}\n";
}

// Смещения, зависящие от версии игры. Отдельный файл, а не секция Settings.json:
// у них другая жизнь — их правят после обновления игры, а не при настройке.
std::string DefaultGamedataJson() {
    return
        "{\n"
        "  // ЕДИНСТВЕННОЕ место в плагине с числами, зависящими от версии игры.\n"
        "  //\n"
        "  // Указатель на систему сущностей лежит внутри IGameResourceService по этому\n"
        "  // смещению; движок его не отдаёт никак иначе. Без него не прочитать поля\n"
        "  // контроллера игрока: счёт, убийства, смерти, команду.\n"
        "  //\n"
        "  // Если после обновления CS2 итоги матча стали нулями, а в консоли\n"
        "  // [Gamedata] жалуется на смещение — возьмите свежее значение из gamedata\n"
        "  // CS2Fixes (ключ \"GameEntitySystem\") и перезапустите сервер.\n"
        "  // Файл никогда не перезаписывается плагином.\n"
        "  \"GameEntitySystem\": {\n"
        "    \"linux\": 80,\n"
        "    \"windows\": 88\n"
        "  }\n"
        "}\n";
}

std::string SettingsSchemaJson() {
    return
        "{\n"
        "  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n"
        "  \"title\": \"ConnectHistory Settings\",\n"
        "  \"type\": \"object\",\n"
        "  \"additionalProperties\": false,\n"
        "  \"properties\": {\n"
        "    \"$schema\": { \"type\": \"string\" },\n"
        "    \"Debug\": { \"type\": \"boolean\" },\n"
        "    \"ServerId\": {\n"
        "      \"type\": \"integer\", \"minimum\": 0, \"deprecated\": true,\n"
        "      \"description\": \"Устарело, переехало в Server.Id. Читается ради старых конфигов; при наличии обоих выигрывает Server.Id.\"\n"
        "    },\n"
        "    \"DefaultLang\": { \"type\": \"string\" },\n"
        "    \"DisplayTimeZone\": {\n"
        "      \"type\": \"string\",\n"
        "      \"description\": \"UTC, Local или смещение вида +03:00. На базу не влияет.\"\n"
        "    },\n"
        "    \"Server\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": {\n"
        "        \"Id\": { \"type\": \"integer\", \"minimum\": 0 },\n"
        "        \"PublicAddress\": { \"type\": \"string\" }\n"
        "      }\n"
        "    },\n"
        "    \"Database\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": {\n"
        "        \"Host\": { \"type\": \"string\" },\n"
        "        \"Port\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 65535 },\n"
        "        \"Database\": { \"type\": \"string\" },\n"
        "        \"User\": { \"type\": \"string\" },\n"
        "        \"Password\": { \"type\": \"string\" },\n"
        "        \"SslMode\": {\n"
        "          \"enum\": [\"None\", \"Preferred\", \"Required\", \"VerifyCA\", \"VerifyFull\"],\n"
        "          \"description\": \"Preferred и Required шифруют, но не проверяют сертификат — как в целях на C#. VerifyCA/VerifyFull проверяют и требуют, чтобы сертификат сервера был доверенным.\"\n"
        "        },\n"
        "        \"TablePrefix\": { \"type\": \"string\", \"pattern\": \"^[A-Za-z0-9_]{0,16}$\" },\n"
        "        \"ConnectionTimeoutSeconds\": { \"type\": \"integer\", \"minimum\": 1 },\n"
        "        \"CommandTimeoutSeconds\": { \"type\": \"integer\", \"minimum\": 1 }\n"
        "      }\n"
        "    },\n"
        "    \"Collect\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": {\n"
        "        \"GeoIp\": { \"type\": \"boolean\" },\n"
        "        \"PlayerIp\": { \"type\": \"boolean\" },\n"
        "        \"IpHash\": { \"type\": \"boolean\" },\n"
        "        \"IpHashSalt\": { \"type\": \"string\" },\n"
        "        \"MatchStats\": { \"type\": \"boolean\" },\n"
        "        \"Ping\": { \"type\": \"boolean\" },\n"
        "        \"CountSpectatorTime\": { \"type\": \"boolean\" },\n"
        "        \"NicknameHistory\": { \"type\": \"boolean\" },\n"
        "        \"PlayerAggregates\": { \"type\": \"boolean\" },\n"
        "        \"OnlineSnapshots\": { \"type\": \"boolean\" },\n"
        "        \"OnlineSnapshotIntervalSeconds\": { \"type\": \"integer\", \"minimum\": 30 },\n"
        "        \"PingSampleIntervalSeconds\": { \"type\": \"integer\", \"minimum\": 5 }\n"
        "      }\n"
        "    },\n"
        "    \"Storage\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": {\n"
        "        \"SpoolEnabled\": { \"type\": \"boolean\" },\n"
        "        \"SpoolMaxEntries\": { \"type\": \"integer\", \"minimum\": 0 },\n"
        "        \"RetryAttempts\": { \"type\": \"integer\", \"minimum\": 1 },\n"
        "        \"RetryDelaySeconds\": { \"type\": \"integer\", \"minimum\": 1 }\n"
        "      }\n"
        "    },\n"
        "    \"Commands\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": false,\n"
        "      \"properties\": {\n"
        "        \"PlayerCommandsEnabled\": { \"type\": \"boolean\" },\n"
        "        \"CooldownSeconds\": { \"type\": \"integer\", \"minimum\": 0 },\n"
        "        \"LastSeenLimit\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 25 }\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "}\n";
}

std::string MessagesSchemaJson() {
    return
        "{\n"
        "  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\n"
        "  \"title\": \"ConnectHistory Messages\",\n"
        "  \"type\": \"object\",\n"
        "  \"properties\": {\n"
        "    \"$schema\": { \"type\": \"string\" },\n"
        "    \"Messages\": {\n"
        "      \"type\": \"object\",\n"
        "      \"additionalProperties\": {\n"
        "        \"type\": \"object\",\n"
        "        \"additionalProperties\": { \"type\": \"string\" }\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "}\n";
}

std::string ReadmeText() {
    return
        "ConnectHistory - connection history and player analytics\n"
        "========================================================\n"
        "Metamod:Source build (native, C++).\n"
        "\n"
        "Files in this directory:\n"
        "  Settings.json          - main settings (contains the database password!)\n"
        "  Messages.json          - texts for the ch_playtime / ch_lastseen commands\n"
        "  *.schema.json          - JSON Schema; your editor will autocomplete and catch typos\n"
        "\n"
        "SECURITY\n"
        "  * Settings.json holds a password. The plugin keeps it at mode 600 (owner only).\n"
        "  * Give the plugin its OWN MySQL user, limited to its tables:\n"
        "    SELECT, INSERT, UPDATE, CREATE, INDEX, ALTER.\n"
        "  * Use SslMode=Required when the database is not on localhost - otherwise\n"
        "    nicknames, SteamIDs and player IPs travel the network in clear text.\n"
        "\n"
        "MAIN SETTINGS\n"
        "  Server.Id              - server number. MUST differ between servers.\n"
        "                           Was a top-level ServerId before 3.0.1; the old\n"
        "                           spelling is still read, so old configs keep working.\n"
        "  Debug                  - verbose log (prints SteamIDs, nicknames and player IPs).\n"
        "  DisplayTimeZone        - the time zone PLAYERS see times in.\n"
        "                           This build understands \"UTC\", \"Local\" and an offset\n"
        "                           such as \"+03:00\"; IANA names like \"Europe/Moscow\"\n"
        "                           are NOT supported - see the metamod target README.\n"
        "                           The database is ALWAYS UTC.\n"
        "  Database.TablePrefix   - table prefix, ch_ by default\n"
        "  gamedata.json          - the ONE game-version-dependent number: the offset of\n"
        "                           the entity system inside IGameResourceService. Match\n"
        "                           results (score, kills, deaths, team) need it. After a CS2\n"
        "                           update that moves it, take the new value from CS2Fixes\n"
        "                           gamedata (key GameEntitySystem). Never overwritten.\n"
        "  Server.PublicAddress   - public server address, \"ip:port\" or \"host:port\".\n"
        "                           The server process does not know its own public address:\n"
        "                           ConVar ip is the socket bind address, usually 0.0.0.0.\n"
        "\n"
        "WHAT IS COLLECTED (the Collect section)\n"
        "  GeoIp                  - country and city via GeoLite2 (.mmdb next to the plugin)\n"
        "  PlayerIp               - full player IP (personal data)\n"
        "  IpHash + IpHashSalt    - HMAC of the IP: multi-accounts stay visible, the address\n"
        "                           is not stored. An empty salt disables hashing.\n"
        "  MatchStats             - kills, deaths, damage, MVP.\n"
        "                           NOTE: this build does not collect score - the column\n"
        "                           stays NULL. Neither is ping. See docs/DATABASE.md.\n"
        "  CountSpectatorTime     - count spectator time as playtime.\n"
        "                           false subtracts out-of-game time from the aggregate.\n"
        "                           The time itself always goes to spectator_seconds.\n"
        "\n"
        "IF THE DATABASE IS UNAVAILABLE\n"
        "  Records are spooled to data/pending-writes.jsonl and re-sent automatically.\n"
        "  Storage.SpoolMaxEntries caps the file size.\n"
        "\n"
        "COMMANDS (server console only)\n"
        "  ch_status                     - status: database link, queue, last error\n"
        "  ch_reload                     - reload the configuration\n"
        "  ch_playtime <steamid64>       - a player's playtime\n"
        "  ch_lastseen <steamid64>       - a player's recent sessions\n"
        "\n"
        "Full database schema and a query cookbook: docs/DATABASE.md.\n"
        "Panel module: https://github.com/Armatura-Create/ConnectHistory-Flute\n";
}

}  // namespace ch
